Repository SpartaPoSSG/PoSSG, pull requests merged in 2024-06, with the labels that each got.

#60 Fe/design/#46/login+register
  frontend/src/pages/Login.tsx
  frontend/src/pages/Register.tsx
Labels: fix, Design

#63 Fe/design/#61
  frontend/src/index.css
  frontend/src/pages/Login.tsx
  frontend/src/pages/Register.tsx
  frontend/tailwind.config.js
Labels: Design

#65 Fe/fix/#64/register
  frontend/src/components/Navbars.tsx
  frontend/src/pages/Register.tsx
Labels: fix, Design

#69 fix : 포트폴리오 회색 박스에 , 직무 추천 띄우기
  frontend/src/pages/Portfolio.tsx
Labels: fix, Feat

#70 Fe/fix/#68/delete
  frontend/src/api/possgAxios.ts
  frontend/src/components/ProjectFile.tsx
  frontend/src/components/ProjectFolder.tsx
  frontend/src/interfaces/Interfaces.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/Portfolio.tsx
  frontend/src/pages/ProjectDetail.tsx
Labels: fix
